---
- name: LOKI | TASK | Ensure config directory exist.
  file:
    path: "{{ loki_config_dir }}"
    state: directory

- name: LOKI | TASK | Copy loki config file
  template: "src=config.yml.j2 dest={{ loki_config_dir }}/config.yml"
  notify:
    - restart loki
