---
- name: LOKI | TASK | Ensure {{ loki_home_dir }} exists.
  file:
    path: {{ loki_home_dir }}
    state: directory

- name: LOKI | TASK | Check if the current version is installed.
  stat:
    path: "{{ loki_home_dir }}/loki-{{ loki_version }}"
  register: loki_version_stats

- name: LOKI | TASK | Download loki.
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v{{ loki_version }}/loki-linux-amd64.zip"
    dest: "{{ loki_home_dir }}/loki-linux-amd64.zip"
    force: yes
  when: loki_version_stats.stat.exists == false

- name: LOKI | TASK | Unpack tarball.
  unarchive:
    src: "{{ loki_home_dir }}/loki-linux-amd64.zip"
    dest: "{{ loki_home_dir }}"
    remote_src: yes
  when: loki_version_stats.stat.exists == false

- name: LOKI | TASK | Rename downloaded promtail file.
  command: "mv {{ loki_home_dir }}/loki-linux-amd64 {{ loki_home_dir }}/loki-{{ loki_version }}"
  when: loki_version_stats.stat.exists == false

- name: LOKI | TASK | Copy systemd service file.
  template:
    src: loki.service.j2
    dest: /etc/systemd/system/loki.service
  notify:
    - restart loki

- name: LOKI | TASK | Create symlink.
  file:
    src: "{{ loki_home_dir }}/loki-{{ loki_version }}"
    dest: "{{ loki_executable }}"
    state: link
  notify:
    - restart loki
